const EventProgramsSeed = [
  {
    name: "AI Innovation Summit 2024",
    date: "2024-02-15",
    organizer: "Tech Hub Ghana",
    presenter: "Dr. Michael Owusu",
    programName: "AI Foundations and Applications",
    participants: 120,
    eventType: "workshop",
    category: "ai",
    beneficiaries: "students",
    description: "Introductory AI summit for students and developers.",
    roomNumber: 1,
    roomType: "conference",
    status: "OCCUPIED",
  },
  {
    name: "Cybersecurity Awareness 2024",
    date: "2024-03-10",
    organizer: "SecureNet Africa",
    presenter: "Daniel Boateng",
    programName: "Digital Safety Basics",
    participants: 90,
    eventType: "teaching",
    category: "networking",
    beneficiaries: "business",
    description: "Training on cyber threats and prevention.",
    roomNumber: 2,
    roomType: "seminar",
    status: "RESERVED",
  },
  {
    name: "Robotics Bootcamp 2024",
    date: "2024-04-05",
    organizer: "Future Makers Lab",
    presenter: "Eng. Isaac Mensah",
    programName: "Intro to Robotics Systems",
    participants: 75,
    eventType: "workshop",
    category: "robotics",
    beneficiaries: "students",
    description: "Hands-on robotics training session.",
    roomNumber: 3,
    roomType: "conference",
    status: "AVAILABLE",
  },
  {
    name: "Data Science Workshop 2024",
    date: "2024-05-12",
    organizer: "Insight Data Hub",
    presenter: "Grace Ntim",
    programName: "Python for Data Analysis",
    participants: 110,
    eventType: "teaching",
    category: "data science",
    beneficiaries: "students",
    description: "Data analysis using Python and visualization tools.",
    roomNumber: 4,
    roomType: "seminar",
    status: "OCCUPIED",
  },
  {
    name: "IoT Smart Systems 2024",
    date: "2024-06-20",
    organizer: "Smart Systems GH",
    presenter: "Linda Nyarko",
    programName: "IoT Integration Basics",
    participants: 80,
    eventType: "discussion",
    category: "iot",
    beneficiaries: "business",
    description: "IoT systems in modern industries.",
    roomNumber: 1,
    roomType: "seminar",
    status: "MAINTENANCE",
  },

  // ─────────────────────────────────────────────
  // 2024–2025 EXPANSION
  // ─────────────────────────────────────────────

  {
    name: "Drone Mapping Conference 2024",
    date: "2024-07-18",
    organizer: "AeroVision Ghana",
    presenter: "Patricia Addo",
    programName: "Drone Survey Systems",
    participants: 95,
    eventType: "video conference",
    category: "drone",
    beneficiaries: "government officials",
    description: "Aerial mapping for agriculture and infrastructure.",
    roomNumber: 2,
    roomType: "conference",
    status: "CHECKOUT",
  },
  {
    name: "Coding Bootcamp 2024",
    date: "2024-08-10",
    organizer: "Code Academy Africa",
    presenter: "Samuel Ofori",
    programName: "Full Stack Development",
    participants: 140,
    eventType: "workshop",
    category: "programming",
    beneficiaries: "students",
    description: "Frontend and backend development training.",
    roomNumber: 3,
    roomType: "conference",
    status: "OCCUPIED",
  },
  {
    name: "Smart Agriculture 2024",
    date: "2024-09-05",
    organizer: "AgriTech Connect",
    presenter: "Emmanuel Badu",
    programName: "IoT Farming Solutions",
    participants: 70,
    eventType: "project",
    category: "iot",
    beneficiaries: "local residents",
    description: "Technology-driven agriculture solutions.",
    roomNumber: 4,
    roomType: "seminar",
    status: "AVAILABLE",
  },
  {
    name: "AI Ethics Forum 2024",
    date: "2024-10-01",
    organizer: "Digital Policy Institute",
    presenter: "Prof. Akua Mensima",
    programName: "Responsible AI",
    participants: 60,
    eventType: "discussion",
    category: "ai",
    beneficiaries: "government officials",
    description: "Ethical considerations in AI deployment.",
    roomNumber: 1,
    roomType: "conference",
    status: "RESERVED",
  },
  {
    name: "Networking Essentials 2024",
    date: "2024-11-11",
    organizer: "Digital Skills Center",
    presenter: "Sandra Mensah",
    programName: "Cisco Fundamentals",
    participants: 85,
    eventType: "teaching",
    category: "networking",
    beneficiaries: "business",
    description: "Networking infrastructure training.",
    roomNumber: 2,
    roomType: "seminar",
    status: "OCCUPIED",
  },

  // ─────────────────────────────────────────────
  // 2025 EVENTS
  // ─────────────────────────────────────────────

  {
    name: "AI Startup Summit 2025",
    date: "2025-01-20",
    organizer: "Startup Connect",
    presenter: "Eunice Aryee",
    programName: "AI Entrepreneurship",
    participants: 130,
    eventType: "workshop",
    category: "ai",
    beneficiaries: "business",
    description: "Startup innovation using AI tools.",
    roomNumber: 3,
    roomType: "conference",
    status: "AVAILABLE",
  },
  {
    name: "Python Data Masterclass 2025",
    date: "2025-02-14",
    organizer: "AI Research Center",
    presenter: "Nana Yeboah",
    programName: "Advanced Python Analytics",
    participants: 115,
    eventType: "teaching",
    category: "data science",
    beneficiaries: "students",
    description: "Advanced Python programming for analytics.",
    roomNumber: 4,
    roomType: "seminar",
    status: "OCCUPIED",
  },
  {
    name: "Robotics Expo 2025",
    date: "2025-03-10",
    organizer: "RoboFuture Africa",
    presenter: "Mildred Kusi",
    programName: "Industrial Robotics",
    participants: 150,
    eventType: "discussion",
    category: "robotics",
    beneficiaries: "local residents",
    description: "Robotics innovation exhibition.",
    roomNumber: 1,
    roomType: "conference",
    status: "CHECKOUT",
  },

  // ─────────────────────────────────────────────
  // 2026 EVENTS (LATEST)
  // ─────────────────────────────────────────────

  {
    name: "AI Future Summit 2026",
    date: "2026-02-10",
    organizer: "Tech Hub Ghana",
    presenter: "Dr. Michael Owusu",
    programName: "Next Gen AI Systems",
    participants: 200,
    eventType: "workshop",
    category: "ai",
    beneficiaries: "students",
    description: "Advanced AI systems and innovation showcase.",
    roomNumber: 2,
    roomType: "conference",
    status: "OCCUPIED",
  },
  {
    name: "Smart City Conference 2026",
    date: "2026-03-18",
    organizer: "GovTech Alliance",
    presenter: "Hon. Patrick Amoah",
    programName: "Urban Digital Transformation",
    participants: 180,
    eventType: "video conference",
    category: "iot",
    beneficiaries: "government officials",
    description: "Smart city planning and IoT integration.",
    roomNumber: 3,
    roomType: "conference",
    status: "RESERVED",
  },
  {
    name: "Digital Skills Outreach 2026",
    date: "2026-04-22",
    organizer: "Community ICT Initiative",
    presenter: "Josephine Tetteh",
    programName: "Basic Computer Training",
    participants: 220,
    eventType: "it training",
    category: "basic computing",
    beneficiaries: "senior citizens",
    description: "Digital literacy for all age groups.",
    roomNumber: 4,
    roomType: "seminar",
    status: "AVAILABLE",
  },

  // ─────────────────────────────────────────────
  // EXTRA RANDOMIZED VARIATIONS (fills to ~60 total)
  // ─────────────────────────────────────────────

  ...Array.from({ length: 44 }).map((_, i) => {
    const year = 2024 + (i % 3);
    const month = String((i % 12) + 1).padStart(2, "0");

    const categories = [
      "ai",
      "iot",
      "robotics",
      "data science",
      "programming",
      "networking",
      "drone",
      "basic computing",
    ];

    const types = [
      "workshop",
      "teaching",
      "meetings",
      "discussion",
      "video conference",
      "project",
    ];

    const statuses = [
      "AVAILABLE",
      "OCCUPIED",
      "MAINTENANCE",
      "CHECKOUT",
      "RESERVED",
    ];

    return {
      id: 100 + i,
      name: `Tech Event ${i + 1}`,
      date: `${year}-${month}-1${i % 9}`,
      organizer: `Org ${i + 1}`,
      presenter: `Presenter ${i + 1}`,
      programName: `Program ${i + 1}`,
      participants: 50 + (i % 150),
      eventType: types[i % types.length],
      category: categories[i % categories.length],
      beneficiaries: "students",
      description: `Generated event record number ${i + 1} for testing system load.`,
      roomNumber: (i % 4) + 1,
      roomType: i % 2 === 0 ? "conference" : "seminar",
      status: statuses[i % statuses.length],
    };
  }),
];

module.exports = EventProgramsSeed;
